#ifndef PTPMESSAGETYPE_H
#define PTPMESSAGETYPE_H

enum PtpMessageType
{
    PTP_MESSSAGE_TYPE_SYNC = 0x0,
    PTP_MESSSAGE_TYPE_PDELAY_REQ = 0x2,
    PTP_MESSSAGE_TYPE_PDELAY_RESP = 0x3,
    PTP_MESSSAGE_TYPE_FOLLOW_UP = 0x8,
    PTP_MESSSAGE_TYPE_PDELAY_RESP_FOLLOW_UP = 0xA,
    PTP_MESSSAGE_TYPE_ANNOUNCE = 0xB,
    PTP_MESSSAGE_TYPE_SIGNALING = 0xC
};

#endif // PTPMESSAGETYPE_H

